from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('bank_detail', views.bank_detail, name='bank_detail'),
    path('customer_detail', views.customer_detail, name='customer_detail'),
    path('supplier_detail', views.supplier_detail, name='supplier_detail'),
    path('business_detail/<str:pk>', views.business_detail, name='business_detail'),
    path('KYC_detail', views.KYC_detail, name='KYC_detail'),
    path('gst_detail', views.gst_detail, name='gst_detail'),
    path('financial_detail', views.financial_detail, name='financial_detail'),
    path('analysis_report', views.analysis_report, name='analysis_report'),
    path('shareholding_detail', views.shareholding_detail, name='shareholding_detail'),
    path('credit_rating', views.credit_rating, name='credit_rating'),
    path('debt_profile', views.debt_profile, name='debt_profile'),
    path('business_profile', views.business_profile, name='business_profile'),
    path('AS26_detail', views.AS26_detail, name='AS26_detail'),
    path('pending_businesses', views.pending_businesses, name='pending_businesses'),
    path('registered_businesses', views.registered_businesses, name='registered_businesses'),
    path('invard_cheque', views.invard_cheque, name='invard_cheque'),
    path('debit_credit', views.debit_credit, name='debit_credit'),
    path('loan_detail', views.loan_detail, name='loan_detail'),
    path('emi_payement', views.emi_payement, name='emi_payement'),
    path('top_credits', views.top_credits, name='top_credits'),
    path('top_debits', views.top_debits, name='top_debits'),
    path('gstr_one', views.gstr_one, name='gstr_one'),
    path('gst_filter', views.gst_filter, name='gst_filter'),
    path('gstr_three', views.gstr_three, name='gstr_three'),
    path('gst_sale', views.gst_sale, name='gst_sale'),
    path('gst_customer', views.gst_customer, name='gst_customer'),
    path('gst_supplier', views.gst_supplier, name='gst_supplier'),
    path('gst_product', views.gst_product, name='gst_product'),
    path('bankdetail_comment', views.bankdetail_comment, name='bankdetail_comment'),
    path('financial_calculations', views.financial_calculations, name='financial_calculations'),
    path('financial_calculations_two', views.financial_calculations_two, name='financial_calculations_two'),
    path('financial_calculations_three', views.financial_calculations_three, name='financial_calculations_three'),
    path('financial_calculations_four', views.financial_calculations_four, name='financial_calculations_four'),
    path('financial_calculations_five', views.financial_calculations_five, name='financial_calculations_five'),
    path('financial_calculations_six', views.financial_calculations_six, name='financial_calculations_six'),
    path('financial_calculations_seven', views.financial_calculations_seven, name='financial_calculations_seven'),
    path('financial_calculations_eight', views.financial_calculations_eight, name='financial_calculations_eight'),
    path('pending_form/<str:pk>', views.pending_form, name='pending_form'),
    path('approved_form/<str:pk>', views.approved_form, name='approved_form'),
    path('fascilate_amount/<str:pk>', views.fascilate_amount, name='fascilate_amount'),
    path('fascilate_amount_save/<str:pk>', views.fascilate_amount_save, name='fascilate_amount_save'),
    path('enter_fascilate_amount/<str:pk>', views.enter_fascilate_amount, name='enter_fascilate_amount'),
    path('reason/<str:pk>', views.reason, name='reason'),
    path('authorisedperson_detail', views.authorisedperson_detail, name='authorisedperson_detail'),
    path('remove_authorisedperson/<int:pk>', views.remove_authorisedperson, name='remove_authorisedperson'),
    path('remove_analysisreport/<int:pk>', views.remove_analysisreport, name='remove_analysisreport'),
    path('remove_creditrating/<int:pk>', views.remove_creditrating, name='remove_creditrating'),
    path('remove/<int:pk>', views.removeobj, name='remove'),
    path('remove_bankdetail/<int:pk>', views.removeobj_bankdetail, name='remove_bankdetail'),
    path('remove_debt_profile/<int:pk>', views.remove_debt_profile, name='remove_debt_profile'),
    path('remove_financialdetail/<int:pk>', views.removeobj_financialdetail, name='remove_financialdetail'),
    path('remove_gstdetail/<int:pk>', views.removeobj_gstdetail, name='remove_gstdetail'),
    path('remove_KYCdetail/<int:pk>', views.remove_KYCdetail, name='remove_KYCdetail'),
    path('remove_shareholding/<int:pk>', views.remove_shareholding, name='remove_shareholding'),
    path('remove_suppliersdetails/<int:pk>', views.remove_suppliersdetails, name='remove_suppliersdetails'),
    path('remove_customerdetail/<int:pk>', views.remove_customerdetail, name='remove_customerdetail'),
    path('remove_AS26detail/<int:pk>', views.remove_AS26detail, name='remove_AS26detail'),
    path('business', views.business, name='business'),
    path('business_info', views.business_info, name='business_info'),
    path('bank_statement', views.bank_statement, name='bank_statement'),
    path('company_details', views.company_details, name='company_details'),
    path('gst_details', views.gst_details, name='gst_details'),
    path('pan_details', views.pan_details, name='pan_details'),
    path('test', views.test, name='test'),
    path('details', views.details, name='details'),
    path('test1/<uuid:pk>', views.test1, name='test1')

]
