# Generated by Django 3.1.7 on 2021-03-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cin_llp_no', models.CharField(blank=True, db_column='CIN_LLP_no', max_length=20, null=True)),
                ('type_of_business', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('business_face_value_discount_rate', models.FloatField(blank=True, null=True)),
                ('gst_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('as_26_detail', models.CharField(blank=True, db_column='AS_26_detail', max_length=20, null=True)),
                ('business_pan_card', models.CharField(blank=True, max_length=16, null=True)),
                ('business_udyog_adhaar', models.CharField(blank=True, max_length=16, null=True)),
                ('business_credit_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('business_financial_statement', models.CharField(blank=True, max_length=20, null=True)),
                ('business_shareholding', models.CharField(blank=True, max_length=20, null=True)),
                ('business_list_of_directors', models.CharField(blank=True, max_length=20, null=True)),
                ('business_credit_report', models.CharField(blank=True, max_length=20, null=True)),
                ('business_debt_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('business_customers', models.CharField(blank=True, max_length=100, null=True)),
                ('business_suppliers', models.CharField(blank=True, max_length=100, null=True)),
                ('business_aoa_moa', models.CharField(blank=True, db_column='business_AOA_MOA', max_length=20, null=True)),
                ('business_address_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('business_board_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('business_coi_deed', models.CharField(blank=True, db_column='business_COI_Deed', max_length=100, null=True)),
                ('business_gumasta', models.CharField(blank=True, db_column='business_Gumasta', max_length=100, null=True)),
                ('business_description', models.CharField(blank=True, max_length=100, null=True)),
                ('business_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('business_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email_id', models.CharField(blank=True, max_length=25, null=True)),
                ('business_user_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('business_user_email_id', models.CharField(blank=True, max_length=25, null=True)),
                ('business_user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('business_user_pan_card', models.CharField(blank=True, max_length=25, null=True)),
                ('business_user_adhaar_card', models.CharField(blank=True, max_length=25, null=True)),
                ('business_user_dob', models.DateField(blank=True, null=True)),
                ('partner_referal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('business_bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('business_bank_account_cancelled_cheque', models.CharField(blank=True, max_length=20, null=True)),
                ('business_bank_account_ifsc_code', models.CharField(blank=True, db_column='business_bank_account_IFSC_code', max_length=10, null=True)),
                ('business_bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('business_mcred_wallet_acc_no', models.CharField(blank=True, max_length=20, null=True)),
                ('business_mcred_wallet_bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_sales_person', models.CharField(blank=True, max_length=30, null=True)),
                ('facility_approved_amount', models.IntegerField(blank=True, null=True)),
                ('entity_mapped', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_validity', models.CharField(blank=True, max_length=100, null=True)),
                ('penal_interest_charges', models.IntegerField(blank=True, null=True)),
                ('margin_period', models.CharField(blank=True, max_length=100, null=True)),
                ('status_of_compliance', models.CharField(blank=True, max_length=100, null=True)),
                ('status_of_due_clearance', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_statement_analysis_report', models.TextField(blank=True, null=True)),
                ('gst_statement_analysis_report', models.TextField(blank=True, null=True)),
                ('facility_assessment_report', models.TextField(blank=True, null=True)),
                ('credit_analysis_report', models.TextField(blank=True, null=True)),
                ('available_facility_limit', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('delay', models.CharField(blank=True, max_length=50, null=True)),
                ('financials', models.CharField(blank=True, max_length=100, null=True)),
                ('since_active', models.CharField(blank=True, max_length=10, null=True)),
                ('total_invoices', models.IntegerField(blank=True, null=True)),
                ('verified_items', models.CharField(blank=True, max_length=100, null=True)),
                ('company_overview', models.TextField(blank=True, null=True)),
                ('history_with_mcred', models.TextField(blank=True, null=True)),
                ('mcred_opinion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investors_business',
                'managed': False,
            },
        ),
    ]
