# Generated by Django 3.1.7 on 2021-04-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={},
        ),
    ]
