# Generated by Django 3.1.7 on 2021-03-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysisreports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofcompany', models.CharField(blank=True, max_length=100, null=True)),
                ('filetype', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('report', models.FileField(blank=True, null=True, upload_to='Analysisreports')),
            ],
        ),
        migrations.CreateModel(
            name='BankstatementDetails_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('AC_No', models.IntegerField(blank=True, max_length=100, null=True)),
                ('AC_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('To_date', models.DateField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Bankstatementdetail')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Business_detail')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='BusinessProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingagency', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date_of_rating', models.DateTimeField()),
                ('amount_of_rating', models.IntegerField(blank=True, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Creditrating')),
            ],
        ),
        migrations.CreateModel(
            name='Customerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('per_tweleve_month_sale', models.IntegerField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Customerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DebtProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lender', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_loan', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_of_loan', models.CharField(blank=True, max_length=100, null=True)),
                ('outstanding_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_of_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Debtprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Financialdetail_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('To_date', models.DateField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='financialdetail')),
            ],
        ),
        migrations.CreateModel(
            name='GSTDetails_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_No', models.IntegerField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('To_date', models.DateField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Gstdetail')),
            ],
        ),
        migrations.CreateModel(
            name='KYCdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofbusinessholder', models.CharField(blank=True, max_length=100, null=True)),
                ('PAN_NO', models.IntegerField(blank=True, null=True)),
                ('Adhar_NO', models.IntegerField(blank=True, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='KYCdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofshareholder', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_of_shareholding', models.IntegerField(blank=True, max_length=100, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Shareholdings')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliersdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase', models.CharField(blank=True, max_length=100, null=True)),
                ('last_tweleve_month_sale', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Suppliersdetails')),
            ],
        ),
    ]
