# Generated by Django 3.1.7 on 2021-03-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('InvestorDashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails_test',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
    ]
