# Generated by Django 3.1.7 on 2021-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDashboards', '0002_businessdetails_test_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails_test',
            name='input_file',
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_AOA_MOA',
            field=models.FileField(blank=True, null=True, upload_to='AOA_MOA'),
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_COI_LLP_certificate',
            field=models.FileField(blank=True, null=True, upload_to='COI_LLP_Certificate'),
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_board_resolution',
            field=models.FileField(blank=True, null=True, upload_to='Board_resolution'),
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_business_profile',
            field=models.FileField(blank=True, null=True, upload_to='Business_Profile'),
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_company_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='company_address_proof'),
        ),
        migrations.AddField(
            model_name='businessdetails_test',
            name='file_pan_card',
            field=models.FileField(blank=True, null=True, upload_to='pan_card'),
        ),
        migrations.AlterField(
            model_name='bankstatementdetails_test',
            name='AC_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='per_tweleve_month_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetails_test',
            name='gst_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareholding',
            name='percentage_of_shareholding',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
