# Generated by Django 3.1.7 on 2021-03-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('InvestorDashboards', '0006_financialdetail_test_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreports',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='creditrating',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='debtprofile',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='shareholding',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
        migrations.AddField(
            model_name='suppliersdetails',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business'),
        ),
    ]
