# Generated by Django 3.1.7 on 2021-03-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDashboards', '0009_authorisedperson_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdetail',
            old_name='Adhar_NO',
            new_name='ID_NO',
        ),
        migrations.RenameField(
            model_name='kycdetail',
            old_name='Nameofbusinessholder',
            new_name='Name_of_directors',
        ),
        migrations.RenameField(
            model_name='kycdetail',
            old_name='PAN_NO',
            new_name='Type_of_ID',
        ),
    ]
