# Generated by Django 3.1.7 on 2021-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDashboards', '0010_auto_20210308_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdetail',
            name='Type_of_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
