# Generated by Django 3.1.7 on 2021-03-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDashboards', '0012_auto_20210315_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='average_monthly_sale',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='total_annual_sale',
        ),
    ]
