# Generated by Django 3.1.7 on 2021-03-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('InvestorDashboards', '0013_auto_20210315_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTDetails_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_No', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Gstdetail')),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
