# Generated by Django 3.1.7 on 2021-03-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('InvestorDashboards', '0014_gstdetails_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisedperson_details',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='user_aadhaar'),
        ),
        migrations.AddField(
            model_name='authorisedperson_details',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='user_pan'),
        ),
        migrations.CreateModel(
            name='As26detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='As26detail')),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
