# Generated by Django 3.1.7 on 2021-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDashboards', '0016_invardchequereturns_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='average_monthly_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='total_annual_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
