# Generated by Django 3.1.7 on 2021-03-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('tests', '0002_loan_details_in_last_tweleve_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI_payement_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('emi_amount', models.IntegerField(blank=True, null=True)),
                ('date_of_transaction', models.IntegerField(blank=True, null=True)),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
