# Generated by Django 3.1.7 on 2021-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_gstdetails_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdetails_new',
            name='domestic_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstdetails_new',
            name='export_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
