# Generated by Django 3.1.7 on 2021-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20210317_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdetails_new',
            name='deviation_from_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstdetails_new',
            name='sales_as_per_gstr_thee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
