# Generated by Django 3.1.7 on 2021-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20210317_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sale', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
