# Generated by Django 3.1.7 on 2021-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_financial_calculations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial_calculations',
            old_name='ebidta_per_m_one',
            new_name='ebidta_per_m_cy',
        ),
        migrations.RenameField(
            model_name='financial_calculations',
            old_name='ebitdta_one',
            new_name='ebidta_per_m_lqy',
        ),
        migrations.RenameField(
            model_name='financial_calculations',
            old_name='sales_one',
            new_name='ebidta_per_m_ly',
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebidta_per_m_py',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebidta_per_m_sqy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebitdta_cy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebitdta_lqy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebitdta_ly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebitdta_py',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='ebitdta_sqy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='sales_cy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='sales_lqy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='sales_ly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='sales_py',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_calculations',
            name='sales_sqy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
