# Generated by Django 3.1.7 on 2021-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
