# Generated by Django 3.1.7 on 2021-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_comments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
