# Generated by Django 3.1.7 on 2021-03-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('tests', '0025_auto_20210320_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliersdetails_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase', models.CharField(blank=True, max_length=100, null=True)),
                ('last_tweleve_month_sale', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Suppliersdetails')),
                ('Total_annual_purchase', models.FloatField(blank=True, null=True)),
                ('avg_monthly_purchase', models.FloatField(blank=True, null=True)),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
