# Generated by Django 3.1.7 on 2021-03-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_auto_20210323_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='autor',
            new_name='author',
        ),
    ]
