# Generated by Django 3.1.7 on 2021-03-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_auto_20210323_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type',
            new_name='title',
        ),
    ]
