# Generated by Django 3.1.7 on 2021-03-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('tests', '0035_auto_20210323_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedsuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('last_tweleve_month_purchase', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_as_per_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
        migrations.CreateModel(
            name='Approvedcustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('last_tweleve_month_sale', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_as_per_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
