# Generated by Django 3.1.7 on 2021-03-31 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0036_approvedcustomers_approvedsuppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
