# Generated by Django 3.1.7 on 2021-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0038_bankstatementdetails_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementdetails_new',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
