# Generated by Django 3.1.7 on 2021-04-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('tests', '0039_bankstatementdetails_new_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='director_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_director', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('DIN_number', models.CharField(blank=True, max_length=100, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='listofdirector')),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
