# Generated by Django 3.1.7 on 2021-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0040_director_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_list',
            name='Pan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
