# Generated by Django 3.1.7 on 2021-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0042_businessdetails_test_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails_test_new',
            name='gst_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
