# Generated by Django 3.1.7 on 2021-04-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_entity_entitybusinessroimapping_entityinvestorrormapping_investor_invoice_transaction_wallet'),
        ('tests', '0043_auto_20210408_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_list',
            name='Aadhar_file',
            field=models.FileField(blank=True, null=True, upload_to='Aadharphoto'),
        ),
        migrations.AddField(
            model_name='director_list',
            name='Aadhar_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CreditRating_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingagency', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_rating', models.DateTimeField()),
                ('amount_of_rating', models.IntegerField(blank=True, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='Creditrating')),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investors.business')),
            ],
        ),
    ]
