# Generated by Django 3.1.7 on 2021-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0044_auto_20210409_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_customers',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gst_products',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gst_sale',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gst_suppliers',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
