# Generated by Django 3.1.7 on 2021-04-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0047_gstr_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstr_one',
            old_name='sales_as_per_gstr_three',
            new_name='domestic_sale',
        ),
        migrations.RenameField(
            model_name='gstr_one',
            old_name='deviation_from_sale',
            new_name='export_sale',
        ),
    ]
